---
- name: Copy the gen folder of border router
  copy: src={{local_gen}}/{{cfg_loc}}/br{{isd}}-{{as}}-{{item}}
        dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}
  with_items: "{{instances}}"
  remote_user: scion
  become: "{{simple_conf|default(false)}}"
  become_user: scion
