---
- name: Copy the gen folder of sibra server
  copy: src={{local_gen}}/{{cfg_loc}}/sb{{isd}}-{{as}}-{{sb}}
        dest={{repo_loc}}/gens/{{ts}}/{{cfg_loc}}
  remote_user: scion
  become: "{{simple_conf|default(false)}}"
  become_user: scion
