---
- name: Install pre-deps
  apt: name=git
- name: Install SCION deployment SSH key
  copy: src=files/deploy.scion dest=/home/scion/.ssh/deploy.scion mode=0400
  remote_user: scion
- name: Make sure GOPATH exists in .profile
  lineinfile: dest=/home/scion/.profile line="export GOPATH=/home/scion/go"
  remote_user: scion
- name: Make sure Go-1.6 is not there anymore
  file: path=/usr/lib/go-1.6 state=absent
- name: Make sure path for Go-1.6 is removed from .profile
  lineinfile: dest=/home/scion/.profile
              line="export PATH=\"/home/scion/.local/bin:/usr/lib/go-1.6/bin:$GOPATH/bin:$PATH\""
              state=absent
  remote_user: scion
- name: Make sure PATH exists in .profile
  lineinfile: dest=/home/scion/.profile
              line="export PATH=\"/home/scion/.local/bin:/usr/local/go/bin:$GOPATH/bin:$PATH\""
  remote_user: scion
- name: Make sure alias for SCION folder exists .profile
  lineinfile: dest=/home/scion/.profile
              line="alias cdscion='cd ~/go/src/github.com/netsec-ethz/scion'"
  remote_user: scion
- name: Make sure scion repo folder exists
  file: path={{repo_loc}} state=directory
  remote_user: scion
- name: Checkout SCION codebase
  git: repo=git@github.com:netsec-ethz/scion.git
       dest={{repo_loc}}
       key_file=~/.ssh/deploy.scion
       version={{scion_version}}
       accept_hostkey=yes
  remote_user: scion
- name: Install all dependencies
  shell: bash --login -c "APTARGS=-y GO_INSTALL=y ./env/deps" chdir={{repo_loc}}
  environment:
    GIT_SSH_COMMAND: 'ssh -i ~/.ssh/deploy.scion'
  remote_user: scion
- name: Copy the basics of the gen directory
  copy: src={{local_gen}}/dispatcher dest={{repo_loc}}/gens/{{ts}}/
  remote_user: scion
- name: Copy the endhost folder
  copy: src={{local_gen}}/ISD{{isd}}/AS{{as}}/endhost dest={{repo_loc}}/gens/{{ts}}/ISD{{isd}}/AS{{as}}/
  remote_user: scion
