---
- name: Create ~root/.ssh and ensure permissions=0700
  file:
    path: ~root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Setup ~root/.ssh/authorized_keys and ensure permissions=0600
  copy:
    src: files/ansible.rsa.pub
    dest: ~root/.ssh/authorized_keys
    owner: root
    group: root
    mode: 0600

- name: Add scion user
  user:
    name: scion
    comment: "SCION user"
    groups: sudo
    shell: /bin/bash

- name: Install the scion sudoers file under /etc/sudoers.d/scion
  copy:
    src: files/scion_sudoers
    dest: /etc/sudoers.d/scion
    owner: root
    group: root

- name: Create ~scion/.ssh and ensure permissions=0700
  file:
    path: ~scion/.ssh
    state: directory
    owner: scion
    group: scion
    mode: 0700

- name: Setup ~scion/.ssh/authorized_keys and ensure permissions=0600
  vars:
    authorized_keys: "{{SCION_KEYS|default('files/authorized_keys-scion')}}"
  copy:
    src: "{{authorized_keys}}"
    dest: ~scion/.ssh/authorized_keys
    owner: scion
    group: scion
    mode: 0600
